/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Microsoft
 */
public class Penilaian extends javax.swing.JFrame {

    /**
     * Creates new form Penilaian
     */
    public Penilaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        absen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mapel1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nilai = new javax.swing.JTextField();
        BtnOk1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penilaian Siswa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 20, 150, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 40, 17);
        getContentPane().add(nama1);
        nama1.setBounds(80, 60, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Absen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 50, 17);
        getContentPane().add(absen);
        absen.setBounds(80, 100, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mapel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 40, 17);
        getContentPane().add(mapel1);
        mapel1.setBounds(80, 140, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nilai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 190, 40, 17);
        getContentPane().add(nilai);
        nilai.setBounds(80, 180, 190, 30);

        BtnOk1.setText("Proses");
        BtnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOk1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOk1);
        BtnOk1.setBounds(110, 230, 90, 23);

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 280, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\terorblade.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -10, 340, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOk1ActionPerformed
        String nama = nama1.getText();
        int Absen = Integer.parseInt(absen.getText());
        String Mapel = mapel1.getText();
        int Nilai = Integer.parseInt(nilai.getText());
        String hasil = "";

        if (Nilai >= 100){
            hasil = "Amazing";
        }
        else if (Nilai >=86 && Nilai <=100)
        {
            hasil = "Sempurna";
        }
        else if (Nilai >=75 && Nilai<=85)
        {
            hasil = "Lulus";
        }else if (Nilai >=0 && Nilai <=75){
            hasil = "Tidak Lulus";
        }else
        hasil="";
        TA.setText("Nama : "+nama+"\n"+"Absen : "+Absen+"\n"+"Mapel : "+Mapel+"\n"+"Nilai mu : "+Nilai+"\n"+"Keterangan : "+ hasil);

    }//GEN-LAST:event_BtnOk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk1;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField absen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel1;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
